name: defect_detector
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - scipy
  - numpy
  - pandas
  - matplotlib
  - pillow
  - scikit-image
  - tqdm
  - pytorch-gpu
  - torchvision
  - ultralytics
  - jupyter

